# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PurrfectPix' do
  use_frameworks!

  pod 'Hashtags'
  pod 'Appirater'
  pod 'SDWebImage'
  pod 'Firebase/Core'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'

end
